name: Render README

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: readme-${{ github.ref }}
  cancel-in-progress: true

jobs:
  render:
    name: Render README
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/insightsengineering/rstudio_4.2.1_bioc_3.15:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Render README
        run: |
          install.packages("magick", quiet = TRUE)
          rmarkdown::render("README.Rmd")
        shell: Rscript {0}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[skip actions] Render README.md"
          file_pattern: README.md thumbs hexwall.png
          commit_user_name: insights-engineering-bot
          commit_user_email: >-
            68416928+insights-engineering-bot@users.noreply.github.com
